-- Create schema (optional)
-- CREATE USER music_user IDENTIFIED BY music123;
-- GRANT CONNECT, RESOURCE TO music_user;

-- Switch to your user
-- ALTER SESSION SET CURRENT_SCHEMA = SYSTEM;

-- Drop existing tables (for reset)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE daily_stats CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE songs CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE artists CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- 1️⃣ Create Artists Table
CREATE TABLE artists (
    artist_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist_name VARCHAR2(100) NOT NULL,
    genre VARCHAR2(50),
    followers NUMBER,
    monthly_listeners NUMBER
);

-- 2️⃣ Create Songs Table
CREATE TABLE songs (
    song_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(100) NOT NULL,
    genre VARCHAR2(50),
    release_date DATE,
    total_views NUMBER,
    artist_id NUMBER,
    CONSTRAINT fk_artist FOREIGN KEY (artist_id) REFERENCES artists(artist_id)
);

-- 3️⃣ Create Daily Stats Table
CREATE TABLE daily_stats (
    stat_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    song_id NUMBER,
    stat_date DATE,
    daily_views NUMBER,
    daily_followers_gain NUMBER,
    CONSTRAINT fk_song FOREIGN KEY (song_id) REFERENCES songs(song_id)
);

-- 4️⃣ Insert Sample Artists
INSERT INTO artists (artist_name, genre, followers, monthly_listeners) VALUES ('The Weeknd', 'Pop', 95000000, 100000000);
INSERT INTO artists (artist_name, genre, followers, monthly_listeners) VALUES ('Sidhu Moosewala', 'Punjabi', 25000000, 32000000);
INSERT INTO artists (artist_name, genre, followers, monthly_listeners) VALUES ('Drake', 'Hip-Hop', 85000000, 95000000);
INSERT INTO artists (artist_name, genre, followers, monthly_listeners) VALUES ('Taylor Swift', 'Pop', 120000000, 150000000);

-- 5️⃣ Insert Sample Songs
INSERT INTO songs (title, genre, release_date, total_views, artist_id) VALUES ('Blinding Lights', 'Pop', TO_DATE('2019-11-29', 'YYYY-MM-DD'), 5500000000, 1);
INSERT INTO songs (title, genre, release_date, total_views, artist_id) VALUES ('295', 'Punjabi', TO_DATE('2021-08-14', 'YYYY-MM-DD'), 980000000, 2);
INSERT INTO songs (title, genre, release_date, total_views, artist_id) VALUES ('God''s Plan', 'Hip-Hop', TO_DATE('2018-01-19', 'YYYY-MM-DD'), 1500000000, 3);
INSERT INTO songs (title, genre, release_date, total_views, artist_id) VALUES ('Anti-Hero', 'Pop', TO_DATE('2022-10-21', 'YYYY-MM-DD'), 1200000000, 4);

-- 6️⃣ Insert Sample Daily Stats
INSERT INTO daily_stats (song_id, stat_date, daily_views, daily_followers_gain)
VALUES (1, TO_DATE('2025-10-01', 'YYYY-MM-DD'), 300000, 2000);
INSERT INTO daily_stats (song_id, stat_date, daily_views, daily_followers_gain)
VALUES (2, TO_DATE('2025-10-01', 'YYYY-MM-DD'), 180000, 4000);
INSERT INTO daily_stats (song_id, stat_date, daily_views, daily_followers_gain)
VALUES (3, TO_DATE('2025-10-01', 'YYYY-MM-DD'), 220000, 1500);
INSERT INTO daily_stats (song_id, stat_date, daily_views, daily_followers_gain)
VALUES (4, TO_DATE('2025-10-01', 'YYYY-MM-DD'), 500000, 2500);

COMMIT;