
-- Create Artists table with full details
CREATE TABLE artists (
    artist_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    stage_name VARCHAR2(50),
    dob DATE,
    nationality VARCHAR2(50),
    genre VARCHAR2(50),
    followers NUMBER DEFAULT 0,
    monthly_listeners NUMBER DEFAULT 0
);

-- Insert singers
INSERT INTO artists (full_name, stage_name, dob, nationality, genre, followers, monthly_listeners) 
VALUES ('Shubhdeep Singh Sidhu', 'Sidhu Moosewala', TO_DATE('1993-06-11','YYYY-MM-DD'), 'Indian', 'Punjabi', 25000000, 32000000);

INSERT INTO artists (full_name, stage_name, dob, nationality, genre, followers, monthly_listeners) 
VALUES ('Shubh', 'Shubh', TO_DATE('1997-11-13','YYYY-MM-DD'), 'Indian', 'Punjabi', 5000000, 8000000);

INSERT INTO artists (full_name, stage_name, dob, nationality, genre, followers, monthly_listeners) 
VALUES ('Aubrey Drake Graham', 'Drake', TO_DATE('1986-10-24','YYYY-MM-DD'), 'Canadian', 'Hip-Hop', 85000000, 95000000);

INSERT INTO artists (full_name, stage_name, dob, nationality, genre, followers, monthly_listeners) 
VALUES ('Marshall Bruce Mathers III', 'Eminem', TO_DATE('1972-10-17','YYYY-MM-DD'), 'American', 'Hip-Hop', 70000000, 90000000);

INSERT INTO artists (full_name, stage_name, dob, nationality, genre, followers, monthly_listeners) 
VALUES ('Justin Drew Bieber', 'Justin Bieber', TO_DATE('1994-03-01','YYYY-MM-DD'), 'Canadian', 'Pop', 120000000, 140000000);

INSERT INTO artists (full_name, stage_name, dob, nationality, genre, followers, monthly_listeners) 
VALUES ('Jubin Nautiyal', 'Jubin Nautiyal', TO_DATE('1989-06-14','YYYY-MM-DD'), 'Indian', 'Bollywood', 20000000, 25000000);

INSERT INTO artists (full_name, stage_name, dob, nationality, genre, followers, monthly_listeners) 
VALUES ('Prem Dhillon', 'Prem Dhillon', TO_DATE('1995-12-10','YYYY-MM-DD'), 'Indian', 'Punjabi', 6000000, 7000000);

INSERT INTO artists (full_name, stage_name, dob, nationality, genre, followers, monthly_listeners) 
VALUES ('Navaan Sandhu', 'Navaan Sandhu', TO_DATE('1992-08-05','YYYY-MM-DD'), 'Indian', 'Punjabi', 4000000, 5000000);

INSERT INTO artists (full_name, stage_name, dob, nationality, genre, followers, monthly_listeners) 
VALUES ('Atif Aslam', 'Atif Aslam', TO_DATE('1983-03-12','YYYY-MM-DD'), 'Pakistani', 'Bollywood', 30000000, 35000000);

INSERT INTO artists (full_name, stage_name, dob, nationality, genre, followers, monthly_listeners) 
VALUES ('Jassie Gill', 'Jassie Gill', TO_DATE('1988-12-26','YYYY-MM-DD'), 'Indian', 'Punjabi', 18000000, 22000000);

INSERT INTO artists (full_name, stage_name, dob, nationality, genre, followers, monthly_listeners) 
VALUES ('Babbal Rai', 'Babbal Rai', TO_DATE('1985-09-27','YYYY-MM-DD'), 'Indian', 'Punjabi', 10000000, 12000000);

COMMIT;

 
